version: "3.3"
services:
 mysql:
  image: mysql:latest
  container_name: mysql
  ports:
       - "3306:3306"
  environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=vollmed-api
      - MYSQL_USER=hen1
      - MYSQL_PASSWORD=password
  volumes:
      - dbdata:/var/lib/mysql
  restart: always

volumes:
  dbdata:
